version: '3.8'

services:
  # MySQL Database for ProductService
  mysql:
    image: mysql:8.0
    container_name: stylenest-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: productsdb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - stylenest-network

  # RabbitMQ Message Broker
  rabbitmq:
    image: rabbitmq:3-management
    container_name: stylenest-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"   # AMQP port
      - "15672:15672" # Management UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - stylenest-network

  # Redis for CartService (for future use)
  redis:
    image: redis:7-alpine
    container_name: stylenest-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - stylenest-network

volumes:
  mysql_data:
  rabbitmq_data:
  redis_data:

networks:
  stylenest-network:
    driver: bridge
