global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Spring Boot Actuator Prometheus endpoints
  - job_name: 'spring-actuator'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - apigateway:8085
          - orderservice:8082
          - productservice:8081
          - authservice:8080

  # RabbitMQ Prometheus plugin (enabled, port 15692)
  - job_name: 'rabbitmq'
    metrics_path: /metrics
    static_configs:
      - targets: ['rabbitmq:15692']

  # .NET services (optional). If you add prometheus-net, expose /metrics
  # - job_name: 'dotnet-services'
  #   metrics_path: /metrics
  #   static_configs:
  #     - targets: ['paymentservice:5080','cartservice:5025']

