# Global configuration for all services
spring:
  cloud:
    config:
      server:
        git:
          uri: file:///${user.home}/config-repo
          clone-on-start: true
          default-label: main

# Common monitoring configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    prometheus:
      access: unrestricted
  prometheus:
    metrics:
      export:
        enabled: true

# Common logging configuration
logging:
  level:
    "[org.springframework.amqp]": INFO
    "[org.springframework.cloud]": INFO
    "[com.stylenest]": INFO